# start port
server:
  port: 8887


spring:
  application:
    name: spring-cloud-consumer

logging:
  level:
    root: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
